import {
  ChecklistItemDTO,
  GeneratePRChecklistResponse
} from '../../application/use-cases/GeneratePRChecklistUseCase.js';
import { getGitHubConfig } from '../../config/github.js';

/**
 * チェックリストをMarkdown形式に変換するフォーマッター
 */
export class ChecklistMarkdownFormatter {
  private static readonly COMMENT_MARKER = '<!-- review-dojo-checklist -->';

  /**
   * チェックリストをMarkdown形式に変換
   */
  format(result: GeneratePRChecklistResponse): string {
    const lines: string[] = [];

    // Hidden marker for comment identification
    lines.push(ChecklistMarkdownFormatter.COMMENT_MARKER);
    lines.push('');
    lines.push('## :clipboard: Review Knowledge Checklist');
    lines.push('');

    if (result.checklist.length === 0) {
      return this.formatEmpty(lines);
    }

    return this.formatWithItems(lines, result);
  }

  /**
   * 知見が見つからない場合のフォーマット
   */
  private formatEmpty(lines: string[]): string {
    lines.push(':white_check_mark: No relevant knowledge items found for the changed files.');
    lines.push('');
    lines.push(this.getFooter());
    return lines.join('\n');
  }

  /**
   * 知見がある場合のフォーマット
   */
  private formatWithItems(
    lines: string[],
    result: GeneratePRChecklistResponse
  ): string {
    // Summary section
    lines.push('Based on the changed files, here are relevant review points from past PRs:');
    lines.push('');
    lines.push('### Summary');
    lines.push(result.summary);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Group by severity
    const bySeverity = this.groupBySeverity(result.checklist);

    // Critical items
    if (bySeverity.critical.length > 0) {
      lines.push('### :rotating_light: Critical');
      lines.push('');
      this.formatItems(lines, bySeverity.critical);
    }

    // Warning items
    if (bySeverity.warning.length > 0) {
      lines.push('### :warning: Warning');
      lines.push('');
      this.formatItems(lines, bySeverity.warning);
    }

    // Info items
    if (bySeverity.info.length > 0) {
      lines.push('### :information_source: Info');
      lines.push('');
      this.formatItems(lines, bySeverity.info);
    }

    lines.push(this.getFooter());
    return lines.join('\n');
  }

  /**
   * チェックリストアイテムのフォーマット
   */
  private formatItems(lines: string[], items: ChecklistItemDTO[]): void {
    items.forEach((item, index) => {
      lines.push(`#### ${index + 1}. ${item.title}`);
      lines.push(`- [ ] ${item.checkItem}`);
      lines.push('');
      lines.push('<details>');
      lines.push('<summary>Details</summary>');
      lines.push('');
      lines.push(`- **Category**: ${item.category}`);
      lines.push(`- **Knowledge ID**: \`${item.knowledgeId}\``);
      lines.push('');
      lines.push('</details>');
      lines.push('');
      lines.push('---');
      lines.push('');
    });
  }

  /**
   * 重要度でグループ化
   *
   * Note: Severity値は domain/value-objects/Severity.ts で
   * 'critical' | 'warning' | 'info' のいずれかに制限されているため、
   * これら3つ以外の値は存在しません。
   */
  private groupBySeverity(items: ChecklistItemDTO[]): {
    critical: ChecklistItemDTO[];
    warning: ChecklistItemDTO[];
    info: ChecklistItemDTO[];
  } {
    return {
      critical: items.filter(i => i.severity === 'critical'),
      warning: items.filter(i => i.severity === 'warning'),
      info: items.filter(i => i.severity === 'info')
    };
  }

  /**
   * フッター生成
   */
  private getFooter(): string {
    const { webUrl, orgName } = getGitHubConfig();
    const timestamp = new Date().toISOString();
    return `\n<sub>:robot: Generated by [review-dojo](${webUrl}/${orgName}/review-dojo) | Last updated: ${timestamp}</sub>`;
  }
}
